name: Next.js CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
      - '.github/workflows/next_ci.yml'
  pull_request:
    paths:
      - 'front/**'
      - '.github/workflows/next_ci.yml'
  workflow_dispatch:

jobs:
  lint-and-build:
    name: Next.js project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 #v4.2.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'front/pnpm-lock.yaml'

      - name: Install dependencies
        run: cd front && pnpm install --frozen-lockfile

      - name: Run Biome lint
        run: cd front && pnpm run lint

      - name: Build Next.js
        run: cd front && pnpm run build
